/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-29 08:17:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class todo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"tbody\").on(\"click\",\"a\",function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tvar todoNo = $(this).attr(\"href\");\r\n");
      out.write("\t\t\tif($(this).parents(\"tr\").next().css(\"display\")==\"none\"){\r\n");
      out.write("\t\t\t\t$(this).parents(\"tr\").next().show();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(this).parents(\"tr\").next().hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$(\"tbody\").on(\"click\",\"#btn-todo-com\",function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tvar no = $(this).parent().children(\"input\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"completeTodo.jsp\",\r\n");
      out.write("\t\t\t\tdata:{no:no},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tvar htmlContents = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(result.data, function(index,item){\r\n");
      out.write("\t\t\t\t\t\tif(result.resultCode == \"S\" && result.data.length != 0){\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<tr name='\"+item.no+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\"+item.no+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td><a href=\"+item.no+\">\"+item.title+\"</a></td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\"+item.dates+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\"+item.completed+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\tif(item.completed == \"예\"){\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents+= \"<button class='btn btn-danger btn-xs' id='btn-todo-del'>삭제</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+item.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents += \"<button class='btn btn-success btn-xs' id='btn-todo-com'>처리</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+item.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<tr style='display:none;'>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>할 일</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td colspan='4'>\"+item.contents+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"tbody\").empty().html(htmlContents);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$(\"tbody\").on(\"click\",\"#btn-todo-del\",function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tvar no = $(this).parent().children(\"input\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"deleteTodo.jsp\",\r\n");
      out.write("\t\t\t\tdata:{no:no},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tvar htmlContents = \"\";\r\n");
      out.write("\t\t\t\t\t$.each(result.data, function(index,item){\r\n");
      out.write("\t\t\t\t\t\tif(result.resultCode == \"S\" && result.data.length != 0){\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<tr name='\"+item.no+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\"+item.no+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td><a href=\"+item.no+\">\"+item.title+\"</a></td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\"+item.dates+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\"+item.completed+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\tif(item.completed == \"예\"){\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents+= \"<button class='btn btn-danger btn-xs' id='btn-todo-del'>삭제</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+item.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents += \"<button class='btn btn-success btn-xs' id='btn-todo-com'>처리</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+item.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<tr style='display:none;'>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td>할 일</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<td colspan='4'>\"+item.contents+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$(\"tbody\").empty().html(htmlContents);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$(\"#btn-add-todo\").click(function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tvar title = $(\":input[name=title]\").val();\r\n");
      out.write("\t\t\tvar dates = $(\":input[name=dates]\").val();\r\n");
      out.write("\t\t\tvar contents = $(\":input[name=contents]\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"addTodo.jsp\",\r\n");
      out.write("\t\t\t\tdata:{title:title,dates:dates,contents:contents},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\tvar htmlContents = \"\";\r\n");
      out.write("\t\t\t\t\tif(result.resultCode == \"S\"){\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<tr name='\"+result.data.no+\"'>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\"+result.data.no+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td><a href=\"+result.data.no+\">\"+result.data.title+\"</a></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\"+result.data.dates+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\"+result.data.completed+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\tif(result.data.completed == \"예\"){\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents+= \"<button class='btn btn-danger btn-xs' id='btn-todo-del'>삭제</button>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+result.data.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<button class='btn btn-success btn-xs' id='btn-todo-com'>처리</button>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+result.data.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"</td>\"\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<tr style='display:none;'>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>할 일</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td colspan='4'>\"+result.data.contents+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"tbody\").append(htmlContents);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"responseTodos.jsp\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tvar htmlContents = \"\";\r\n");
      out.write("\t\t\t\t$.each(result.data, function(index,item){\r\n");
      out.write("\t\t\t\t\tif(result.resultCode == \"S\" && result.data.length != 0){\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<tr name='\"+item.no+\"'>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\"+item.no+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td><a href=\"+item.no+\">\"+item.title+\"</a></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\"+item.dates+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\"+item.completed+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\tif(item.completed == \"예\"){\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents+= \"<button class='btn btn-danger btn-xs' id='btn-todo-del'>삭제</button>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+item.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents += \"<button class='btn btn-success btn-xs' id='btn-todo-com'>처리</button>\";\r\n");
      out.write("\t\t\t\t\t\t\thtmlContents+= \"<input type='hidden' name='todo-no' value=\"+item.no+\">\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"</td>\"\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<tr style='display:none;'>\";\t\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td>할 일</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"<td colspan='4'>\"+item.contents+\"</td>\";\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtmlContents += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"tbody\").empty().html(htmlContents);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h1>Todo List</h1>\r\n");
      out.write("\t\t<form class=\"well form-horizontal\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-2\">제목</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"title\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-2\">날짜</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"dates\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\t\r\n");
      out.write("\t\t\t\t<label class=\"control-label col-sm-2\">내용</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" name=\"contents\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-9 col-sm-offset-2 text-right\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-default btn-md\" id=\"btn-add-todo\">등록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"table table-condensed\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>순번</th>\r\n");
      out.write("\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t<th>날짜</th>\r\n");
      out.write("\t\t\t\t\t<th>완료여부</th>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
