/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-12 07:57:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reporter.imageContainer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import kr.co.jtimes.reporter.imagecontainer.common.dao.TbImageDao;
import kr.co.jtimes.reporter.profile.common.vo.ReporterEmployeeVo;
import java.util.Date;
import kr.co.jtimes.reporter.imagecontainer.common.vo.TbImageVo;
import java.util.List;
import kr.co.jtimes.reporter.profile.common.vo.ReporterEmployeeVo;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/reporter/commons/loginCheck.jsp", Long.valueOf(1504699923853L));
    _jspx_dependants.put("/reporter/commons/reporterNavi.jsp", Long.valueOf(1505129191030L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.jtimes.reporter.imagecontainer.common.vo.TbImageVo");
    _jspx_imports_classes.add("kr.co.jtimes.reporter.profile.common.vo.ReporterEmployeeVo");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("kr.co.jtimes.reporter.imagecontainer.common.dao.TbImageDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      .ck-all input{\r\n");
      out.write("          display: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .form-blank {\r\n");
      out.write("           padding-right: 32px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .text-center{\r\n");
      out.write("          margin-top: 30px;\r\n");
      out.write("          margin-bottom: 50px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .caption{\r\n");
      out.write("           text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 
	if(session.getAttribute("loginReporter") == null) {
		//로그인 완료 후 되돌아갈 url가져오기
		String url = (String) pageContext.getAttribute("url");
		String path = "/reporter/profile/login.jsp?deny=1&returnUrl="+url;
		response.sendRedirect(path);
		
		return;
	}

      out.write('\r');
      out.write('\n');
 pageContext.setAttribute("cp", "img"); 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	ReporterEmployeeVo loginReporter = (ReporterEmployeeVo) session.getAttribute("loginReporter");
    	String cp = (String)pageContext.getAttribute("cp");
    
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t.navbar-inverse .navbar-brand,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:focus,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:focus{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:hover, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:focus {\r\n");
      out.write("  \t  \r\n");
      out.write("  \t  background-color: #990000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-header,\r\n");
      out.write("\t.navbar-form{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpadding-top: 10px;\r\n");
      out.write("\t\tpadding-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-nav > li > a{\r\n");
      out.write("\t\tpadding-top: 25px;\r\n");
      out.write("\t\tpadding-bottom: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar-brand img {\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\t<nav class=\"navbar navbar-static-top navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header \">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"/reporter/\"><img src=\"/commons/img/logo.png\" alt=\"logoImage\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("p".equals(cp)?"active":"");
      out.write("\"><a href=\"/reporter/\"><strong>홈</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown ");
      out.print("news".equals(cp)?"active":"");
      out.write("\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\"><strong>기사 관리</strong><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"/reporter/news/addNews.jsp\">기사 작성</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"/reporter/news/writeList.jsp\">작성 목록</a></li>\r\n");
      out.write("\t\t\t\t\t");

						int loginUserPos =((ReporterEmployeeVo)session.getAttribute("loginReporter")).getReporterPos().getPositionNo();
						if(loginUserPos == 100 ||loginUserPos == 200) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"/reporter/news/confirmNews.jsp\">결재 목록</a></li>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown ");
      out.print("img".equals(cp)?"active":"");
      out.write("\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\"><strong>사진 관리</strong><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"/reporter/imageContainer/\">사진 검색</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"/reporter/imageContainer/addPicture.jsp\">사진 등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"#\">소분류3</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("de4".equals(cp)?"active":"");
      out.write("\"><a href=\"/reporter/profile/reporterList.jsp\"><strong>기자 관리</strong></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t");
if(loginReporter == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("log".equals(cp)?"active":"");
      out.write("\"><a href=\"/reporter/profile/login.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span>\r\n");
      out.write("\t\t\t\t\t\t<strong>로그인</strong></a></li>\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"/reporter/profile/profile.jsp\"><strong>프로필 확인</strong></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/reporter/profile/reporterLogout.jsp\"><span class=\"glyphicon glyphicon-log-out\"></span><strong>로그아웃</strong></a></li>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\"> \r\n");
      out.write("         <ul class=\"nav nav-tabs navcontents\">\r\n");
      out.write("            <li class=\"active originalrevision\"><a href=\"#\" id=\"N\">원본</a></li>\r\n");
      out.write("            <li><a href=\"#\" id=\"Y\">수정본</a></li>\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("                <a id=\"category\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">카테고리\r\n");
      out.write("                <span class=\"caret\"></span></a>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                \t<li><a href=\"#\" id=\"categoryAll\">전체</a></li>\r\n");
      out.write("                    <li><a href=\"#\" id=\"10\">시사</a></li>\r\n");
      out.write("                    <li><a href=\"#\" id=\"20\">경제</a></li>\r\n");
      out.write("                    <li><a href=\"#\" id=\"40\">연예</a></li>\r\n");
      out.write("                    <li><a href=\"#\" id=\"30\">스포츠</a></li> \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>      \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("            <div class=\"row text-center well\">\r\n");
      out.write("              <form class=\"form-inline\" name=\"frm\" action=\"index.do\" enctype=\"application/x-www-form-urlencoded\">\r\n");
      out.write("                 <div class=\"form-group form-blank\">\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                          <select name=\"titleAuthorCategory\" id=\"titleAuthorCategory\" class=\"form-control\">\r\n");
      out.write("                          \t  <option value=\"optAll\">전체</option>\r\n");
      out.write("                              <option value=\"optTitle\">제목</option>\r\n");
      out.write("                              <option value=\"optWriter\">작성자</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("                       </div>\r\n");
      out.write("\r\n");
      out.write("                       <div class=\"form-group\">\r\n");
      out.write("                           <input type=\"text\" class=\"form-control\" id=\"searchWord\" name=\"searchWord\">\r\n");
      out.write("                       </div>\r\n");
      out.write("\r\n");
      out.write("                 </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group form-blank\">\r\n");
      out.write("                         <input type=\"date\" class=\"form-control\" name=\"beginDate\" id=\"beginDate\"> ~ <input type=\"date\" class=\"form-control\" name=\"endDate\" id=\"endDate\">\r\n");
      out.write("                   </div>\r\n");
      out.write("               \r\n");
      out.write("                    <div class=\"form-group ck-all form-blank\">\r\n");
      out.write("                       <label for=\"ck-png\" class=\"btn btn-default\">png</label>\r\n");
      out.write("                       <input type=\"checkbox\" id=\"ck-png\" name=\"png\">\r\n");
      out.write("                       \r\n");
      out.write("                       <label for=\"ck-jpg\" class=\"btn btn-default\">jpg</label>\r\n");
      out.write("                       <input type=\"checkbox\" id=\"ck-jpg\" name=\"jpg\">\r\n");
      out.write("                       \r\n");
      out.write("                       <label for=\"ck-bmp\" class=\"btn btn-default\">bmp</label>\r\n");
      out.write("                       <input type=\"checkbox\" id=\"ck-bmp\" name=\"bmp\">\r\n");
      out.write("                       \r\n");
      out.write("                       <label for=\"ck-gif\" class=\"btn btn-default\">gif</label>\r\n");
      out.write("                       <input type=\"checkbox\" id=\"ck-gif\" name=\"gif\">\r\n");
      out.write("                   </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" name=\"formBtn\" id=\"searchBtn\" onclick=\"search(event)\">검색</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                   <div class=\"form-group\">\r\n");
      out.write("                        <a href=\"addPicture.jsp\"><label for=\"\" class=\"btn btn-default\">이미지등록</label></a>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </form>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <div class=\"row \">\r\n");
      out.write("        \t<div class=\"panel panel-default panel-body\" id=\"img-box\">\r\n");
      out.write("\t\t        ");

		        	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
					TbImageDao tbImageDao = new TbImageDao();
		            List<TbImageVo> tbImageList = tbImageDao.getImageSelectAlterStateMain();            		
		        	for(TbImageVo voList : tbImageList) {
		        		String path = voList.getImgPath();
		        		String title = voList.getImgTitle();
		        		String regDate = sdf.format(voList.getImgRegdate());
		        		String reporterNo = voList.getReporter().getReporterName();
		        		String category = voList.getCategory().getCategoryName();
		        		String explanation = voList.getImgAlt();
		        		String location = voList.getImgLocation();
		        		String type = voList.getImgType();
		        
      out.write("\r\n");
      out.write("\t\t        \t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t                    <div class=\"thumbnail\" style=\"width: 250px; height: 300px;\">\r\n");
      out.write("\t\t                        <a href=\"pictureContainer.jsp?path=");
      out.print(path );
      out.write("&title=");
      out.print(title );
      out.write("&regDate=");
      out.print(regDate );
      out.write("&reporterNo=");
      out.print(reporterNo );
      out.write("&category=");
      out.print(category );
      out.write("&explanation=");
      out.print(explanation );
      out.write("&location=");
      out.print(location );
      out.write("&type=");
      out.print(type );
      out.write("\">\r\n");
      out.write("\t\t                            <img src=\"/imgdata/");
      out.print(path );
      out.write("\" width=\"50%\" id=\"img-path\"/>\r\n");
      out.write("\t\t                            <div class=\"caption\" >\r\n");
      out.write("\t\t                                <h4 id=\"img-title\">");
      out.print(title );
      out.write("</h4>\r\n");
      out.write("\t\t                                <p id=\"img-regdate\">");
      out.print(regDate );
      out.write("</p>\r\n");
      out.write("\t\t                                <p id=\"img-reproterno\">");
      out.print(reporterNo );
      out.write("</p>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </a>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t        ");
 
		        	}
		        
      out.write("   \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\" style=\"text-align: center\">\r\n");
      out.write("            <div class=\"label label-primary\" >\r\n");
      out.write("                <label id=\"expend\" style=\"width: 500px; cursor: pointer;\" class=\"glyphicon glyphicon-chevron-down\">  펼치기</label>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    // 원본 수정본을 선택시 선택한 곳의 버튼 모양 변경\r\n");
      out.write("    var navContentsList = document.querySelectorAll(\".nav-tabs > li:nth-child(1)>a, .nav-tabs > li:nth-child(2)>a\");\r\n");
      out.write("    for(var index=0; index < navContentsList.length; index++) {\r\n");
      out.write("        var navContentsListItem = navContentsList.item(index);\r\n");
      out.write("        \r\n");
      out.write("        navContentsListItem.addEventListener(\"click\", function(event) {\r\n");
      out.write("            var liNodeList = document.querySelectorAll(\".nav-tabs > li:nth-child(1), .nav-tabs > li:nth-child(2)\");\r\n");
      out.write("            for(var index2=0; index2 < liNodeList.length; index2++) {\r\n");
      out.write("                liNodeList.item(index2).setAttribute(\"class\", \"\");\r\n");
      out.write("            }\r\n");
      out.write("            event.target.parentNode.setAttribute(\"class\", \"active originalrevision\");\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // 체크박스형식으로 이미지 변경\r\n");
      out.write("    var navExtensionList = document.querySelectorAll(\".ck-all > label:nth-child(n+1)\");\r\n");
      out.write("    for(var navExtensionListIncrease=0; navExtensionListIncrease < navExtensionList.length; navExtensionListIncrease++) {\r\n");
      out.write("        var navExtensionListItem = navExtensionList.item(navExtensionListIncrease);\r\n");
      out.write("            navExtensionListItem.addEventListener('click', function(){\r\n");
      out.write("                this.classList.toggle(\"btn-success\");\r\n");
      out.write("            });\r\n");
      out.write("    }   \r\n");
      out.write("    \r\n");
      out.write(" // 원본 -> 수정본, 수정본 -> 원본이미지 보이게 만들기\r\n");
      out.write("    var liBtnList = document.querySelectorAll(\".nav-tabs > li:nth-child(1)>a, .nav-tabs > li:nth-child(2)>a\");\r\n");
      out.write("    \r\n");
      out.write("    for(index=0; index < liBtnList.length; index++) {\r\n");
      out.write("\t\tvar liBtn = liBtnList.item(index);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tliBtn.addEventListener(\"click\", function(event) {\r\n");
      out.write("            \r\n");
      out.write("\t\t\t// 초기화 함수\r\n");
      out.write("\t\t\ttapId = event.target.id;\r\n");
      out.write("            beginIndex = 1;\r\n");
      out.write("       \t \tendIndex = 8;\r\n");
      out.write("       \t \t\r\n");
      out.write("       \t \t\r\n");
      out.write("            \r\n");
      out.write("       \t \tvar xhr = new XMLHttpRequest();\r\n");
      out.write("            \r\n");
      out.write("            xhr.onreadystatechange = function() {\r\n");
      out.write("                if(xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                    var jsonText = xhr.responseText;\r\n");
      out.write("                    var arr = JSON.parse(jsonText);\r\n");
      out.write("                    console.log(arr);\r\n");
      out.write("                    var html = \"\";\r\n");
      out.write("                    for(var i=0; i < arr.length; i++) {\r\n");
      out.write("                    \tvar img = arr[i];\r\n");
      out.write("                    \tconsole.log(img.Alt + \" \" + img.category.categoryName);\r\n");
      out.write("                    \thtml += '<div class=\"col-xs-3\">';\r\n");
      out.write("\t                    html += '<div class=\"thumbnail\" style=\"width: 250px; height: 300px;\">';\r\n");
      out.write("\t                    html += '<a href=\"pictureContainer.jsp?path='+img.imgPath+'&title='+img.imgTitle+'&regDate='+img.imgRegdate+'&reporterNo='+img.reporter.reporterName+'&category='+img.category.categoryName+'&explanation='+img.imgAlt+'&location='+img.imgLocation+'&type='+img.imgType+'\">';\r\n");
      out.write("\t                    html += '<img src=\"/imgdata/'+img.imgPath+'\" width=\"50%\" id=\"img-path\"/>';\r\n");
      out.write("\t                    html += '<div class=\"caption\" >';\r\n");
      out.write("\t                    html += '<h4 id=\"img-title\">'+img.imgTitle+'</h4>';\r\n");
      out.write("\t                    html += '<p id=\"img-regdate\">'+img.imgRegdate+'</p>';\r\n");
      out.write("\t                    html += '<p id=\"img-reproterno\">'+img.reporter.reporterName+'</p>';\r\n");
      out.write("\t                    html += '</div>';\r\n");
      out.write("\t                    html += '</a>';\r\n");
      out.write("\t                    html += '</div>';\r\n");
      out.write("\t                    html += '</div>';\r\n");
      out.write("\r\n");
      out.write("                    };\r\n");
      out.write("                    \r\n");
      out.write("                    document.getElementById(\"img-box\").innerHTML = html;\r\n");
      out.write("                    \r\n");
      out.write("            \t}\r\n");
      out.write("            }\r\n");
      out.write("            xhr.open(\"GET\", \"/index.do?bino=\"+beginIndex+\"&eino=\"+endIndex+\"&tapid=\"+tapId+\"&categoryId=\"+categoryId);\r\n");
      out.write("            \r\n");
      out.write("            xhr.send(null);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // 펼치기 클릭 시 8개씩 나오게 만듬\r\n");
      out.write("    // 초기화 함수\r\n");
      out.write("\tvar beginIndex = 1;\r\n");
      out.write("    var endIndex = 8;\r\n");
      out.write("\tvar tapId = \"\";\r\n");
      out.write("\t\r\n");
      out.write("    document.getElementById(\"expend\").addEventListener(\"click\", function(event){\r\n");
      out.write("    \t\t\r\n");
      out.write("    \tvar expendId = document.getElementById(\"expend\").id\r\n");
      out.write("    \ttapId = document.querySelector(\".originalrevision > a\").id;\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar xhr = new XMLHttpRequest();\r\n");
      out.write("        \r\n");
      out.write("        xhr.onreadystatechange = function() {\r\n");
      out.write("            if(xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                var jsonTextTap = xhr.responseText;\r\n");
      out.write("                var arrTap = JSON.parse(jsonTextTap);\r\n");
      out.write("                \r\n");
      out.write("                var htmlTap = \"\";\r\n");
      out.write("                for(var a=0; a < arrTap.length; a++) {\r\n");
      out.write("                \tvar imgTap = arrTap[a];\r\n");
      out.write("                \thtmlTap += '<div class=\"col-xs-3\">';\r\n");
      out.write("                \thtmlTap += '<div class=\"thumbnail\" style=\"width: 250px; height: 300px;\">';\r\n");
      out.write("                \thtmlTap += '<a href=\"pictureContainer.jsp?path='+imgTap.imgPath+'&title='+imgTap.imgTitle+'&regDate='+imgTap.imgRegdate+'&reporterNo='+imgTap.reporter.reporterName+'&category='+imgTap.category.categoryName+'&explanation='+imgTap.imgAlt+'&location='+imgTap.imgLocation+'&type='+imgTap.imgType+'\">';\r\n");
      out.write("                \thtmlTap += '<img src=\"/imgdata/'+imgTap.imgPath+'\" width=\"50%\" id=\"img-path\"/>';\r\n");
      out.write("                \thtmlTap += '<div class=\"caption\" >';\r\n");
      out.write("                \thtmlTap += '<h4 id=\"img-title\">'+imgTap.imgTitle+'</h4>';\r\n");
      out.write("                \thtmlTap += '<p id=\"img-regdate\">'+imgTap.imgRegdate+'</p>';\r\n");
      out.write("                \thtmlTap += '<p id=\"img-reproterno\">'+imgTap.reporter.reporterName+'</p>';\r\n");
      out.write("                    htmlTap += '</div>';\r\n");
      out.write("                    htmlTap += '</a>';\r\n");
      out.write("                    htmlTap += '</div>';\r\n");
      out.write("                    htmlTap += '</div>';\r\n");
      out.write("                }\r\n");
      out.write("                document.getElementById(\"img-box\").innerHTML += htmlTap;\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 펼치기 버튼 누를시 8씩 증가하는 함수\r\n");
      out.write("        beginIndex += 8;\r\n");
      out.write("        endIndex += 8;\r\n");
      out.write("        xhr.open(\"GET\", \"/index.do?bino=\"+beginIndex+\"&eino=\"+endIndex+\"&tapid=\"+tapId+\"&expendId=\"+expendId+\"&categoryId=\"+categoryId);\r\n");
      out.write("        \r\n");
      out.write("        xhr.send(null);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // 카테고리를 변경 할 때마다 이름값을 메인 카테고리 라인에 넣기\r\n");
      out.write("    // 초기화 함수\r\n");
      out.write("    // categoryId: 시사의id값, 경제의id값, 스포츠의id값, 연예의id값\r\n");
      out.write("    // categoryName: a테그 안에 있는 html화면에 보이는 text값\r\n");
      out.write("     var categoryId = \"\";\r\n");
      out.write("     var categoryList = document.querySelectorAll(\".dropdown-menu li a\");\r\n");
      out.write("     for(index=0; index < categoryList.length; index++) {\r\n");
      out.write("         var categoryItem = categoryList.item(index);\r\n");
      out.write("         \r\n");
      out.write("         // 원본/수정본의 id값을 가져옴\r\n");
      out.write("         tapId = document.querySelector(\".originalrevision > a\").id;\r\n");
      out.write("         \r\n");
      out.write("         categoryItem.addEventListener(\"click\", function(event) {\r\n");
      out.write("        \t\r\n");
      out.write("        \t // 초기화 함수\r\n");
      out.write("        \t beginIndex = 1;\r\n");
      out.write("        \t endIndex = 8;\r\n");
      out.write("        \t \r\n");
      out.write("        \t // a테그 안에 있는 html화면에 보이는 text값과 카테고리별 id값을 가져옴\r\n");
      out.write("        \t var categoryName = event.target.innerText;\r\n");
      out.write("             categoryId = event.target.id;\r\n");
      out.write("             \r\n");
      out.write("             document.getElementById(\"category\").innerHTML = categoryName;\r\n");
      out.write("             \r\n");
      out.write("             var xhr = new XMLHttpRequest();\r\n");
      out.write("             \r\n");
      out.write("             xhr.onreadystatechange = function() {\r\n");
      out.write("                 if(xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                     var jsonTextCategory = xhr.responseText;\r\n");
      out.write("                     var arrCategory = JSON.parse(jsonTextCategory);\r\n");
      out.write("                     \r\n");
      out.write("                     var htmlCategory = \"\";\r\n");
      out.write("                     for(i=0; i < arrCategory.length; i++) {\r\n");
      out.write("                     \tvar imgCategory = arrCategory[i];\r\n");
      out.write("\t                     \thtmlCategory += '<div class=\"col-xs-3\">';\r\n");
      out.write("\t                     \thtmlCategory += '<div class=\"thumbnail\" style=\"width: 250px; height: 300px;\">';\r\n");
      out.write("\t                     \thtmlCategory += '<a href=\"pictureContainer.jsp?path='+imgCategory.imgPath+'&title='+imgCategory.imgTitle+'&regDate='+imgCategory.imgRegdate+'&reporterNo='+imgCategory.reporter.reporterName+'&category='+imgCategory.category.categoryName+'&explanation='+imgCategory.imgAlt+'&location='+imgCategory.imgLocation+'&type='+imgCategory.imgType+'\">';\r\n");
      out.write("\t                     \thtmlCategory += '<img src=\"/imgdata/'+imgCategory.imgPath+'\" width=\"50%\" id=\"img-path\"/>';\r\n");
      out.write("\t                     \thtmlCategory += '<div class=\"caption\" >';\r\n");
      out.write("\t                     \thtmlCategory += '<h4 id=\"img-title\">'+imgCategory.imgTitle+'</h4>';\r\n");
      out.write("\t                     \thtmlCategory += '<p id=\"img-regdate\">'+imgCategory.imgRegdate+'</p>';\r\n");
      out.write("\t                     \thtmlCategory += '<p id=\"img-reproterno\">'+imgCategory.reporter.reporterName+'</p>';\r\n");
      out.write("\t \t                    htmlCategory += '</div>';\r\n");
      out.write("\t \t                    htmlCategory += '</a>';\r\n");
      out.write("\t \t                    htmlCategory += '</div>';\r\n");
      out.write("\t \t                    htmlCategory += '</div>';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write(" \t                   \r\n");
      out.write("                     };\r\n");
      out.write("                     \r\n");
      out.write("                     document.getElementById(\"img-box\").innerHTML = htmlCategory;\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("             \t}\r\n");
      out.write("             }\r\n");
      out.write("             xhr.open(\"GET\", \"/index.do?bino=\"+beginIndex+\"&eino=\"+endIndex+\"&tapid=\"+tapId+\"&categoryId=\"+categoryId);\r\n");
      out.write("             \r\n");
      out.write("             xhr.send(null);\r\n");
      out.write("\r\n");
      out.write("         }); \r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("     // 제목 작성자 검색기능\r\n");
      out.write("      function search(event){\r\n");
      out.write("    \t event.preventDefault();\r\n");
      out.write("\t    \t\r\n");
      out.write("    \t \t // 초기화 함수\r\n");
      out.write("\t     \t beginIndex = 1;\r\n");
      out.write("\t     \t endIndex = 8;\r\n");
      out.write("        \t tapId = document.querySelector(\".originalrevision > a\").id;\t\r\n");
      out.write("  \r\n");
      out.write("             var xhr = new XMLHttpRequest();\r\n");
      out.write("             \r\n");
      out.write("             xhr.onreadystatechange = function() {\r\n");
      out.write("                 if(xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                     var jsonTextSearch = xhr.responseText;\r\n");
      out.write("                     var arrSearch = JSON.parse(jsonTextSearch);\r\n");
      out.write("                     \r\n");
      out.write("                     var htmlSearch = \"\";\r\n");
      out.write("                     for(i=0; i < arrSearch.length; i++) {\r\n");
      out.write("                     \tvar imgSearch = arrSearch[i];\r\n");
      out.write("                     \t//Console.log(imgSearch.imgPath);\r\n");
      out.write("                     \t//Console.log(imgSearch.imgTitle);\r\n");
      out.write("                     \t//Console.log(imgSearch.imgRegdate);\r\n");
      out.write("                     \t//Console.log(imgSearch.reporter.reporterNo);\r\n");
      out.write("\t                     \thtmlSearch += '<div class=\"col-xs-3\">';\r\n");
      out.write("\t                     \thtmlSearch += '<div class=\"thumbnail\" style=\"width: 250px; height: 300px;\">';\r\n");
      out.write("\t                     \thtmlSearch += '<a href=\"pictureContainer.jsp?path='+imgSearch.imgPath+'&title='+imgSearch.imgTitle+'&regDate='+imgSearch.imgRegdate+'&reporterNo='+imgSearch.reporter.reporterName+'&category='+imgSearch.category.categoryName+'&explanation='+imgSearch.imgAlt+'&location='+imgSearch.imgLocation+'&type='+imgSearch.imgType+'\">';\r\n");
      out.write("\t                     \thtmlSearch += '<img src=\"/imgdata/'+imgSearch.imgPath+'\" width=\"50%\" id=\"img-path\"/>';\r\n");
      out.write("\t                     \thtmlSearch += '<div class=\"caption\" >';\r\n");
      out.write("\t                     \thtmlSearch += '<h4 id=\"img-title\">'+imgSearch.imgTitle+'</h4>';\r\n");
      out.write("\t                     \thtmlSearch += '<p id=\"img-regdate\">'+imgSearch.imgRegdate+'</p>';\r\n");
      out.write("\t                     \thtmlSearch += '<p id=\"img-reproterno\">'+imgSearch.reporter.reporterName+'</p>';\r\n");
      out.write("\t                     \thtmlSearch += '</div>';\r\n");
      out.write("\t                     \thtmlSearch += '</a>';\r\n");
      out.write("\t\t \t                htmlSearch += '</div>';\r\n");
      out.write("\t\t \t                htmlSearch += '</div>';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write(" \t                   \r\n");
      out.write("                     };\r\n");
      out.write("                     \r\n");
      out.write("                     document.getElementById(\"img-box\").innerHTML = htmlSearch;\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("             \t}\r\n");
      out.write("             }\r\n");
      out.write("             xhr.open(\"POST\", \"/index.do\");\r\n");
      out.write("             var obj = {\r\n");
      out.write("            \t bino: beginIndex,\r\n");
      out.write("            \t eino: endIndex,\r\n");
      out.write("            \t tapid: tapId,\r\n");
      out.write("            \t categoryId: categoryId,\r\n");
      out.write("            \t opt: document.getElementById(\"titleAuthorCategory\").value,\r\n");
      out.write("            \t keyword: document.getElementById(\"searchWord\").value,\r\n");
      out.write("            \t beginDate: document.getElementById(\"beginDate\").value,\r\n");
      out.write("            \t endDate: document.getElementById(\"endDate\").value,\r\n");
      out.write("            \t png: document.getElementById(\"ck-png\").checked?\"png\":\"nopng\",\r\n");
      out.write("            \t jpg: document.getElementById(\"ck-jpg\").checked?\"jpg\":\"nojpg\",\r\n");
      out.write("            \t bmp: document.getElementById(\"ck-bmp\").checked?\"bmp\":\"nobmp\",\r\n");
      out.write("            \t gif: document.getElementById(\"ck-gif\").checked?\"gif\":\"nogif\"\r\n");
      out.write("             };\r\n");
      out.write("            var data = makeQueryString(obj);\r\n");
      out.write("            xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("            xhr.send(data);\r\n");
      out.write("    \t}   \r\n");
      out.write("    \r\n");
      out.write("     \tfunction makeQueryString(obj) {\r\n");
      out.write("     \t\tvar param = Object.keys(obj).map(function(key) {\r\n");
      out.write("     \t\t\treturn [key, obj[key]].join(\"=\")\r\n");
      out.write("     \t\t}).join(\"&\");\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\treturn param;\r\n");
      out.write("     \t}\r\n");
      out.write("     \r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
