/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-12 01:33:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.jtimes.profile.common.vo.UserVo;

public final class addUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/commons/clientNavi.jsp", Long.valueOf(1505179754791L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.jtimes.profile.common.vo.UserVo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.container {\r\n");
      out.write("\t\twidth: 1024px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	pageContext.setAttribute("cp", "add");

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");

	String cp = (String) pageContext.getAttribute("cp");
  
  	UserVo userLogin = (UserVo) session.getAttribute("userLogin");
  
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \t.navbar-inverse .navbar-brand,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:focus,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:focus{\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("  \t.navbar-inverse .navbar-nav > .active > a, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:hover, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:focus {\r\n");
      out.write("  \t  color: white;\r\n");
      out.write("  \t  background-color: #990000;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar-header,\r\n");
      out.write("\t.navbar-form{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpadding-top: 10px;\r\n");
      out.write("\t\tpadding-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-nav > li > a{\r\n");
      out.write("\t\tpadding-top: 25px;\r\n");
      out.write("\t\tpadding-bottom: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-brand img {\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav.navbar-nav a strong {\r\n");
      out.write("font-size : 20px;\r\n");
      out.write("line-height:20px;\r\n");
      out.write("vertical-align:bottom;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("  </style>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/index.jsp\"><img src=\"/commons/img/logo.png\" alt=\"logoImage\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"");
      out.print("eve".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/events.jsp\"><strong>시사</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("eco".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/economy.jsp\"><strong>경제</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("spo".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/sports.jsp\"><strong>스포츠</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("ent".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/entertainment.jsp\"><strong>연예</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("join".equals(cp)?"active":"" );
      out.write("\"><a href=\"/citizenrep/list.jsp\"><strong>참여마당</strong></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("    ");
if(userLogin == null) { 
      out.write("\r\n");
      out.write("      <li class=\"");
      out.print("add".equals(cp)?"active":"" );
      out.write("\"><a href=\"/profile/addUser.jsp\"><span class=\"glyphicon glyphicon-user\"></span> 회원가입</a></li>\r\n");
      out.write("      <li class=\"");
      out.print("log".equals(cp)?"active":"" );
      out.write("\"><a href=\"/profile/userLogin.jsp?returnURL=");
      out.print(pageContext.getAttribute("url") );
      out.write("\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그인</a></li>\r\n");
      out.write("     ");
} else { 
      out.write("\r\n");
      out.write("     \t<li class=\"");
      out.print("fix".equals(cp)?"active":"" );
      out.write("\"><a href=\"/profile/profileFix.jsp\">프로필 수정</a></li>\r\n");
      out.write("    \t<li><a href=\"/profile/logout.jsp?returnURL=");
      out.print(pageContext.getAttribute("url") );
      out.write("\"><span class=\"glyphicon glyphicon-log-out\">로그아웃</span></a></li>\r\n");
      out.write("     ");
} 
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-offset-2 col-sm-8\">\r\n");
      out.write("            \t<div class=\"col-sm-offset-2 col-sm-8 panel panel-body\">\r\n");
      out.write("\t                <h1>회원가입</h1>\r\n");
      out.write("\t                ");

	                	final String FAIL_CODE_DUP_ID = "1";
	                	final String FAIL_CODE_NULL = "2";
	                	
	                	String failCode = request.getParameter("fail");
	                
      out.write("\r\n");
      out.write("\t                \r\n");
      out.write("\t                ");
if(FAIL_CODE_DUP_ID.equals(failCode)) {
      out.write("\r\n");
      out.write("\t                \t<div class=\"alert alert-danger\">\r\n");
      out.write("\t                \t\t<strong>오류</strong> 유효한 값을 입력해주세요.\r\n");
      out.write("\t                \t</div>\r\n");
      out.write("\t                ");
}
      out.write("\r\n");
      out.write("\t                ");
 
						if(FAIL_CODE_NULL.equals(failCode) ) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"alert alert-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>오류</strong> 유효한 정보를 입력해주세요.\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t                \r\n");
      out.write("\t             \r\n");
      out.write("\t                <form class=\"well\" method=\"post\" action=\"add.jsp\">\r\n");
      out.write("\t\r\n");
      out.write("\t                    <div class=\"input-group\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("   \t\t\t\t\t\t\t<input id=\"id\" type=\"text\" class=\"form-control\" name=\"id\" placeholder=\"아이디\" type=\"text\" onkeyup=\"fn_press_han(this);\"  onblur=\"fn_press_han(this);\" style=\"ime-mode:disabled;\"/>\r\n");
      out.write("   \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("\t                    <div class=\"form-group\" id=\"idCheck\" name=\"idCheck\"></div>\r\n");
      out.write("\t                     <!-- \r\n");
      out.write("\t\t\t\t\t\t \t브라켓 부트스트랩 데모7-폼에 \r\n");
      out.write("\t\t\t\t\t\t \tsuccess, fail 있음\r\n");
      out.write("\t\t\t\t\t\t -->\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t    <input id=\"password\" type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"비밀번호\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" id=\"pwdCheck\"></div>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                    <div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-ok\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t    <input id=\"repassword\" type=\"password\" class=\"form-control\" name=\"repassword\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" id=\"rePwdCheck\"></div>\r\n");
      out.write("\t                    <div class=\"form-group\">\r\n");
      out.write("\t\t                    <div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t    <span class=\"input-group-addon\"> 이름 </span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input id=\"name\" type=\"text\" class=\"form-control\" name=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t                   \t\r\n");
      out.write("\t\t                   \t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t    <span class=\"input-group-addon\">Email</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input id=\"email\" type=\"text\" class=\"form-control\" name=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("       \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("       \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t        \t<select class=\"form-control\" name=\"question\">\r\n");
      out.write("\t\t\t\t  \t\t\t\t<option value=\"q1\">나의 아버지 성함은?</option>\r\n");
      out.write("\t\t\t\t  \t\t\t\t<option value=\"q2\">나의 어머니 성함은?</option>\r\n");
      out.write("\t\t\t\t  \t\t\t\t<option value=\"q3\">나의 출신 고등학교는?</option>\r\n");
      out.write("\t\t\t\t  \t\t\t\t<option value=\"q4\">나의 출신 중학교는?</option>\r\n");
      out.write("\t\t\t\t  \t\t\t\t<option value=\"q5\">나의 출신 초등학교는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t    <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-pushpin\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"answer\" placeholder=\"응답\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t                    <div class=\"form-group\">\r\n");
      out.write("\t                    \t\r\n");
      out.write("\t                        <button class=\"btn btn-lg btn-danger btn-block\" type=\"submit\">가입하기</button>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t             </div>\r\n");
      out.write("\t             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/* 한글입력 방지 */\r\n");
      out.write("function fn_press_han(obj)\r\n");
      out.write("{\r\n");
      out.write("    //좌우 방향키, 백스페이스, 딜리트, 탭키에 대한 예외\r\n");
      out.write("    if(event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 37 || event.keyCode == 39\r\n");
      out.write("    || event.keyCode == 46 ) return;\r\n");
      out.write("    //obj.value = obj.value.replace(/[\\a-zㄱ-ㅎㅏ-ㅣ가-힣]/g, '');\r\n");
      out.write("    var regexp = /[\\ㄱ-ㅎㅏ-ㅣ가-힣]/g;\r\n");
      out.write("    console.log(obj);\r\n");
      out.write("    if (regexp.test(obj.value)) {\r\n");
      out.write("    \tobj.value = \"\";\r\n");
      out.write("    } \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tdocument.getElementById(\"id\").addEventListener(\"blur\",function(event) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar xhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txhr.onreadystatechange = function() {\r\n");
      out.write("\t\t\tif(xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("\t\t\t\tvar data = xhr.responseText;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar htmlContent = \"\";\r\n");
      out.write("\t\t\t\tif(data === \"1\") {//중복된 아이디가 없을 때\r\n");
      out.write("\t\t\t\t\thtmlContent +=\"<p style='color: green'>생성 가능한 아이디 입니다.</p>\";\r\n");
      out.write("\t\t\t\t} else if (data === \"3\") {// 중복된 아이디가 있을 때\r\n");
      out.write("\t\t\t\t\thtmlContent +=\"<p>아이디를 입력하세요.(영문)</p>\";\r\n");
      out.write("\t\t\t\t} else if (data === \"2\"){\r\n");
      out.write("\t\t\t\t\thtmlContent +=\"<p style='color: red'>중복된 아이디가 이미 존재합니다.</p>\"\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"idCheck\").innerHTML = htmlContent;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\txhr.open(\"GET\", \"/profile/idCheck.jsp?id=\"+document.getElementById(\"id\").value);\r\n");
      out.write("\txhr.send(null);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"repassword\").addEventListener(\"blur\",function(event) {\r\n");
      out.write("\t\tvar pwd = document.getElementById(\"password\").value;\r\n");
      out.write("\t\tvar repwd = document.getElementById(\"repassword\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("//\t\talert(pwd.length);\r\n");
      out.write("\t\tvar htmlContents;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pwd === \"\" || repwd === \"\") {\r\n");
      out.write("\t\t\thtmlContents = \"<p>비밀번호를 입력해주세요.</p>\";\r\n");
      out.write("\t\t} else if(pwd === repwd) {\r\n");
      out.write("\t\t\thtmlContents = \"<p style='color: green'>비밀번호가 일치합니다.</p>\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\thtmlContents = \"<p style='color: red'>비밀번호가 일치하지않습니다.</p>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"rePwdCheck\").innerHTML = htmlContents\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"password\").addEventListener(\"blur\",function(event) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar pwd = document.getElementById(\"password\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pwd === \"\") {\r\n");
      out.write("\t\t\thtmlContents = \"<p>비밀번호를 입력해주세요. (8자리이상 14자리이하)</p>\";\r\n");
      out.write("\t\t} else if(pwd.length < 8 || pwd.length > 14) {\r\n");
      out.write("\t\t\thtmlContents = \"<p style='color: red'>비밀번호를 8자리이상 14자리이하로 입력해주세요.</p>\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\thtmlContents = \"<p style='color: green'>사용가능한 비밀번호 입니다.</p>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"pwdCheck\").innerHTML = htmlContents;\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
