/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-13 06:53:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.citizenrep;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.jtimes.common.criteria.Criteria;
import java.sql.SQLException;
import kr.co.jtimes.citizenrep.util.StringUtils;
import kr.co.jtimes.util.DateUtils;
import kr.co.jtimes.citizenrep.vo.CitizenRepVo;
import java.util.List;
import java.util.List;
import kr.co.jtimes.citizenrep.dao.CitizenRepDao;
import kr.co.jtimes.profile.common.vo.UserVo;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/commons/clientNavi.jsp", Long.valueOf(1505274185250L));
    _jspx_dependants.put("/commons/clientFooter.jsp", Long.valueOf(1505205741237L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.co.jtimes.common.criteria.Criteria");
    _jspx_imports_classes.add("kr.co.jtimes.citizenrep.dao.CitizenRepDao");
    _jspx_imports_classes.add("kr.co.jtimes.profile.common.vo.UserVo");
    _jspx_imports_classes.add("kr.co.jtimes.citizenrep.util.StringUtils");
    _jspx_imports_classes.add("kr.co.jtimes.util.DateUtils");
    _jspx_imports_classes.add("kr.co.jtimes.citizenrep.vo.CitizenRepVo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>JTimes :: 시민 제보</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".container {\r\n");
      out.write("\twidth: 1024px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		pageContext.setAttribute("cp", "join");
		pageContext.setAttribute("url",  request.getRequestURI() + "?" + request.getQueryString());
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		//한 화면에 표시할 데이터 행의 갯수
		final int rowsPerPage = 10;
		//한 화면에 표시할 페이지 네비게이션 갯수
		final int naviPerPage = 5;

		//현재 페이지 번호 계산
		int p = StringUtils.strToNumber(request.getParameter("p"), 1);
		CitizenRepDao citizenRepDao = new CitizenRepDao();
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");

	String cp = (String) pageContext.getAttribute("cp");
  
  	UserVo userLogin = (UserVo) session.getAttribute("userLogin");
  
      out.write("\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \t.navbar-inverse .navbar-brand,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:focus,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:focus{\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("  \t.navbar-inverse .navbar-nav > .active > a, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:hover, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:focus {\r\n");
      out.write("  \t  color: white;\r\n");
      out.write("  \t  background-color: #990000;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar-header,\r\n");
      out.write("\t.navbar-form{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpadding-top: 10px;\r\n");
      out.write("\t\tpadding-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-nav > li > a{\r\n");
      out.write("\t\tpadding-top: 25px;\r\n");
      out.write("\t\tpadding-bottom: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-brand img {\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.nav.navbar-nav a strong {\r\n");
      out.write("font-size : 20px;\r\n");
      out.write("line-height:20px;\r\n");
      out.write("vertical-align:bottom;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("  </style>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/index.jsp\"><img src=\"/commons/img/logo.png\" alt=\"logoImage\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"");
      out.print("eve".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/events.jsp\"><strong>시사</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("eco".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/economy.jsp\"><strong>경제</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("spo".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/sports.jsp\"><strong>스포츠</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("ent".equals(cp)?"active":"" );
      out.write("\"><a href=\"/news/entertainment.jsp\"><strong>연예</strong></a></li>\r\n");
      out.write("      <li class=\"");
      out.print("join".equals(cp)?"active":"" );
      out.write("\"><a href=\"/citizenrep/list.jsp\"><strong>참여마당</strong></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("    ");

    	String url = request.getRequestURI() + (request.getQueryString() == null? "" : ("?" + request.getQueryString()));
    	if(userLogin == null) { 
    
    
      out.write("\r\n");
      out.write("      <li class=\"");
      out.print("add".equals(cp)?"active":"" );
      out.write("\"><a href=\"/profile/addUser.jsp\"><span class=\"glyphicon glyphicon-user\"></span> 회원가입</a></li>\r\n");
      out.write("      <li class=\"");
      out.print("log".equals(cp)?"active":"" );
      out.write("\"><a href=\"/profile/userLogin.jsp?returnURL=");
      out.print(url );
      out.write("\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그인</a></li>\r\n");
      out.write("     ");
} else { 
      out.write("\r\n");
      out.write("     \t<li class=\"");
      out.print("fix".equals(cp)?"active":"" );
      out.write("\"><a href=\"/profile/profileFix.jsp\">프로필 수정</a></li>\r\n");
      out.write("    \t<li><a href=\"/profile/logout.jsp?returnURL=");
      out.print(url );
      out.write("\"><span class=\"glyphicon glyphicon-log-out\">로그아웃</span></a></li>\r\n");
      out.write("     ");
} 
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		try {
	
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<h2 class=\"well\">\r\n");
      out.write("\t\t\t\t참여마당<small> - 구독자가 만드는 기사</small>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>날짜</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");

							List<CitizenRepVo> gongji = citizenRepDao.getAllCitRepMaster();
							if(gongji.size()>=3){
							for(int i = 0; i<3; i++){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"background-color: mistyrose;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(gongji.get(i).getCitizenRepNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"/citizenrep/detail.jsp?bno=");
      out.print(gongji.get(i).getCitizenRepNo() );
      out.write('"');
      out.write('>');
      out.print(gongji.get(i).getCitizenRepTitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(gongji.get(i).getWriter().getId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(DateUtils.yyyymmddhhmmss(gongji.get(i).getCitizenRepCreateDate()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
	}} else{
							for(CitizenRepVo vo : gongji){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\"background-color: mistyrose;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(vo.getCitizenRepNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"/citizenrep/detail.jsp?bno=");
      out.print(vo.getCitizenRepNo() );
      out.write('"');
      out.write('>');
      out.print(vo.getCitizenRepTitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(vo.getWriter().getId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(DateUtils.yyyymmddhhmmss(vo.getCitizenRepCreateDate()) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
	
						}}
							int totalRows = citizenRepDao.getTotalRows();						//전체행 조회
							int totalPages = (int) Math.ceil((double)totalRows/rowsPerPage);	//전체 페이지 갯수 계산
							int totalNaviBlocks = (int) Math.ceil((double)totalPages/naviPerPage);	//현재 페이지 네비게이션 블록번호 계산
							int currentNaviBlock = (int) Math.ceil((double)p/naviPerPage);		//페이지 네비 표시할 시작,끝 페이지번호 계산
							int beginPage = (currentNaviBlock-1)*naviPerPage+1;
							int endPage = (currentNaviBlock*naviPerPage);
							if(currentNaviBlock == totalNaviBlocks){
								endPage = totalPages;
							}	
							int beginIndex = (p-1)*rowsPerPage +1;
							int endIndex = p*rowsPerPage;
							Criteria criteria = new Criteria();
							criteria.setBeginIndex(beginIndex);
							criteria.setEndIndex(endIndex);
							List<CitizenRepVo> citizenReps = citizenRepDao.getCitReps(criteria);
							for (CitizenRepVo repVo : citizenReps) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(repVo.getCitizenRepNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/citizenrep/detail.jsp?bno=");
      out.print(repVo.getCitizenRepNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(repVo.getCitizenRepTitle());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(repVo.getWriter().getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(DateUtils.yyyymmddhhmmss(repVo.getCitizenRepCreateDate()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body text-center\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"list.jsp\">맨앞으로</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if(currentNaviBlock >1){
								
      out.write("<li><a href=\"list.jsp?p=");
      out.print(((currentNaviBlock-1)*naviPerPage) );
      out.write("\">&laquo</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }if(p >1){
								
      out.write("<li><a href=\"list.jsp?p=");
      out.print((p-1) );
      out.write("\">&lt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
							for(int i = beginPage; i<=endPage; i++){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"");
      out.print(p==i?"active":"" );
      out.write("\"><a href=\"list.jsp?p=");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
} if(p<totalPages){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"list.jsp?p=");
      out.print((p+1));
      out.write("\">&gt</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
} if(currentNaviBlock<totalNaviBlocks){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"list.jsp?p=");
      out.print((currentNaviBlock+1)*naviPerPage);
      out.write("\">&raquo</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"list.jsp?p=");
      out.print(totalPages );
      out.write("\">맨뒤로</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");

						if (userLogin != null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/citizenrep/form.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-sm pull-right\" id=\"btn-write\">글쓰기</a>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		} catch (SQLException e) {
			e.printStackTrace();
			throw new ServletException(e);
		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<footer class=\"bd-footer text-muted\" style=\"bottom:0; width:100%; height:70px;\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row col-xs-3\">\r\n");
      out.write("\t\t\t\t<h2>J Times</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row col-xs-9\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("    \t\t\t\t<p>Copyright ⓒ All rights reserved <span class=\"glyphicon glyphicon-phone-alt\" aria-hidden=\"true\">010)1111-1111</span></p>\r\n");
      out.write("    \t\t\t\t<p>주소: 서울특별시 종로구 율곡로10길 105 디아망 401호(봉익동 10-1 디아망 401호) 등록일자: 20XX.XX.XX 발행인/편집인: 김형택</p>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"row\">\r\n");
      out.write("    \t\t\t\t| <label><a href=\"/index.jsp\">메인</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"/news/events.jsp\">시사</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"/news/economy.jsp\">경제</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"/news/entertainment.jsp\">연예</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"/news/sports.jsp\">스포츠</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"/citizenrep/list.jsp\">기사제보(참여마당)</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"/sitemap.jsp\">전체서비스</a></label> | \r\n");
      out.write("    \t\t\t\t<label><a href=\"\">맨위로</a></label> |\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</div>\t\t\r\n");
      out.write("\t</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
