/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-06 09:42:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reporter.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.jtimes.reporter.profile.common.vo.ReporterEmployeeVo;

public final class addNews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/reporter/commons/reporterFooter.jsp", Long.valueOf(1504527193683L));
    _jspx_dependants.put("/reporter/commons/reporterNavi.jsp", Long.valueOf(1504683019528L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.jtimes.reporter.profile.common.vo.ReporterEmployeeVo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <META http-equiv=\"Expires\" content=\"-1\"> \r\n");
      out.write("\t<META http-equiv=\"Pragma\" content=\"no-cache\"> \r\n");
      out.write("\t<META http-equiv=\"Cache-Control\" content=\"No-Cache\"> \r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("        .container { margin: 0 auto; width: 1024px;}\r\n");
      out.write("        .margintop {margin-top: 150px;}\r\n");
      out.write("        .picture-container {position: fixed; right:0; top:100px; width:500px; height:100%;}\r\n");
      out.write("        .pic-item{height: 200px;}\r\n");
      out.write("        .pic-item a img{height: 120px;}\r\n");
      out.write("        .pic-item a {cursor: pointer;}\r\n");
      out.write("    </style>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/commons/SmartEditor2/js/service/HuskyEZCreator.js\" charset=\"utf-8\"></script>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\tvar oEditors = [];\r\n");
      out.write("\t\r\n");
      out.write("\tvar sLang = \"ko_KR\";\t// 언어 (ko_KR/ en_US/ ja_JP/ zh_CN/ zh_TW), default = ko_KR\r\n");
      out.write("\t\r\n");
      out.write("\t// 추가 글꼴 목록\r\n");
      out.write("\t//var aAdditionalFontSet = [[\"MS UI Gothic\", \"MS UI Gothic\"], [\"Comic Sans MS\", \"Comic Sans MS\"],[\"TEST\",\"TEST\"]];\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tnhn.husky.EZCreator.createInIFrame({\r\n");
      out.write("\t\t\toAppRef: oEditors,\r\n");
      out.write("\t\t\telPlaceHolder: \"ir1\",\r\n");
      out.write("\t\t\tsSkinURI: \"/commons/SmartEditor2/SmartEditor2Skin.html\",\t\r\n");
      out.write("\t\t\thtParams : {\r\n");
      out.write("\t\t\t\tbUseToolbar : true,\t\t\t\t// 툴바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t\t\tbUseVerticalResizer : true,\t\t// 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t\t\tbUseModeChanger : true,\t\t\t// 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)\r\n");
      out.write("\t\t\t\t//bSkipXssFilter : true,\t\t// client-side xss filter 무시 여부 (true:사용하지 않음 / 그외:사용)\r\n");
      out.write("\t\t\t\t//aAdditionalFontList : aAdditionalFontSet,\t\t// 추가 글꼴 목록\r\n");
      out.write("\t\t\t\tfOnBeforeUnload : function(){\r\n");
      out.write("\t\t\t\t\t//alert(\"완료!\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tI18N_LOCALE : sLang\r\n");
      out.write("\t\t\t}, //boolean\r\n");
      out.write("\t\t\tfOnAppLoad : function(){\r\n");
      out.write("\t\t\t\t//예제 코드\r\n");
      out.write("\t\t\t\t//oEditors.getById[\"ir1\"].exec(\"PASTE_HTML\", [\"로딩이 완료된 후에 본문에 삽입되는 text입니다.\"]);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfCreator: \"createSEditor2\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//----------------------------------------------------------------------------------------------------------------\r\n");
      out.write("\t\tdocument.getElementById(\"btn-hide\").addEventListener(\"click\", function(event){\r\n");
      out.write("\t\t\tevent.stopImmediatePropagation();\r\n");
      out.write("\t\t\tvar btn = document.getElementById(\"btn-hide\");\r\n");
      out.write("\t\t\tvar picCon = document.getElementById(\"picture-container\");\r\n");
      out.write("\t\t\tvar con = document.getElementsByClassName(\"picture-container\")[0];\r\n");
      out.write("\t\t\tconsole.log(picCon.style.display);\r\n");
      out.write("\t\t\tif(picCon.style.display == \"block\" || picCon.style.display == \"\") {\r\n");
      out.write("\t\t\t\tpicCon.style.display = \"none\";\r\n");
      out.write("\t\t\t\tcon.style.width = \"100px\";\r\n");
      out.write("\t\t\t\tbtn.innerHTML = \"<span class='glyphicon glyphicon-menu-left'></span>\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tpicCon.style.display = \"block\";\r\n");
      out.write("\t\t\t\tcon.style.width = \"500px\";\r\n");
      out.write("\t\t\t\tbtn.innerHTML = \"<span class='glyphicon glyphicon-menu-right'></span>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"temp-save\").addEventListener(\"click\", function(event) {\r\n");
      out.write("\t\t\tevent.stopImmediatePropagation();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tvar mainImgFilter = false;\r\n");
      out.write("\tfunction appendContentImg(el){\r\n");
      out.write("\r\n");
      out.write("\t\tvar img = el.firstElementChild;\r\n");
      out.write("\t\tif(mainImgFilter == false){\r\n");
      out.write("\t\t\tmainImgFilter = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"main-img-path\").value = img.src;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar sHTML = \"<div style='width:100%; text-align:center;' align='center'><img src='\"+img.src+\"' style='width:70%;' display='block'/></div>\";\r\n");
      out.write("\t\toEditors.getById[\"ir1\"].exec(\"PASTE_HTML\", [sHTML]);\r\n");
      out.write("\t\tconsole.log(img.src);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction submit(el) {\r\n");
      out.write("\t\toEditors.getById[\"ir1\"].exec(\"UPDATE_CONTENTS_FIELD\", []);\t// 에디터의 내용이 textarea에 적용됩니다.\r\n");
      out.write("\t\tvar newsType = document.getElementById(\"news-type\").value;\r\n");
      out.write("\t\tvar newsCategory = document.getElementById(\"news-category\").value;\r\n");
      out.write("\t\tvar newsLocation = document.getElementById(\"news-location\").value;\r\n");
      out.write("\t\tvar title = document.getElementById(\"news-title\").value;\r\n");
      out.write("\t\tvar contents = document.getElementById(\"ir1\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(newsType == \"\") {\r\n");
      out.write("\t\t\talert(\"종류를 선택하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else if(newsCategory == \"\") {\r\n");
      out.write("\t\t\talert(\"카테고리를 선택하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else if(newsLocation == \"\") {\r\n");
      out.write("\t\t\talert(\"지역을 선택하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else if(title == \"\") {\r\n");
      out.write("\t\t\talert(\"제목을 입력하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else if(contents == \"\") {\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.form.action = \"addNewsProcess.jsp\";\r\n");
      out.write("\t\t\tdocument.form.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	ReporterEmployeeVo loginReporter = (ReporterEmployeeVo) session.getAttribute("loginReporter");
    	String cp = (String)pageContext.getAttribute("cp");
    
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t.navbar-inverse .navbar-brand,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-brand:focus,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:hover,\r\n");
      out.write("\t.navbar-inverse .navbar-nav > li > a:focus{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:hover, \r\n");
      out.write("\t.navbar-inverse .navbar-nav > .active > a:focus {\r\n");
      out.write("  \t  \r\n");
      out.write("  \t  background-color: #990000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-header,\r\n");
      out.write("\t.navbar-form{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpadding-top: 10px;\r\n");
      out.write("\t\tpadding-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-nav > li > a{\r\n");
      out.write("\t\tpadding-top: 25px;\r\n");
      out.write("\t\tpadding-bottom: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.navbar-brand img {\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\t<nav class=\"navbar navbar-static-top navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header \">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"><img src=\"/commons/img/logo.png\" alt=\"logoImage\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("h".equals(cp)?"active":"");
      out.write("\"><a href=\"/reporter/index.jsp\"><strong>홈</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown active\"><a class=\"dropdown-toggle ");
      out.print("u".equals(cp)?"active":"");
      out.write("\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\"><strong>기사 카테고리</strong><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"");
      out.print("tot".equals(cp)?"active":"");
      out.write("\"><a href=\"#\">모든 기사</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"");
      out.print("cul".equals(cp)?"active":"");
      out.write("\"><a href=\"#\">시사</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"");
      out.print("eco".equals(cp)?"active":"");
      out.write("\"><a href=\"#\">경제</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"");
      out.print("sop".equals(cp)?"active":"");
      out.write("\"><a href=\"#\">스포츠</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"");
      out.print("ent".equals(cp)?"active":"");
      out.write("\"><a href=\"#\">연예</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("de2".equals(cp)?"active":"");
      out.write("\"><a href=\"/reporter/news/confirmNews.jsp\"><strong>기사 관리</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("de3".equals(cp)?"active":"");
      out.write("\"><a href=\"#\"><strong>사진 관리</strong></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"");
      out.print("de4".equals(cp)?"active":"");
      out.write("\"><a href=\"#\"><strong>대분류4</strong></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"navbar-form navbar-left\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t");
if(loginReporter == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"/reporter/profile/login.jsp\"><span class=\"glyphicon glyphicon-log-in ");
      out.print("log".equals(cp)?"active":"");
      out.write("\"></span>\r\n");
      out.write("\t\t\t\t\t\t<strong>로그인</strong></a></li>\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"/reporter/profile/profile.jsp\"><strong>프로필 확인</strong></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/reporter/profile/reporterLogout.jsp\"><span class=\"glyphicon glyphicon-log-out ");
      out.print("log".equals(cp)?"active":"");
      out.write("\"><strong>로그아웃</strong></a></li>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
if(loginReporter != null) { 
      out.write("\r\n");
      out.write("\t\t\t<p class=\"navbar-text navbar-right\"><strong>");
      out.print(loginReporter.getReporterName());
      out.write("</strong>님 환영합니다</p>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"margintop\"></div><!-- 네비바를 대신함 -->\r\n");
      out.write("\t\t<form id=\"form\" name=\"form\" class=\"form-horizontal\" action=\"javascript:submit(this)\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"main-img-path\" name=\"mainimgpath\" value=\"\"/> \r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<label class=\"col-xs-1 control-label\">분류</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t<select id=\"news-type\" name=\"newstype\">\r\n");
      out.write("\t\t\t\t\t\t<option selected value=\"\">--- 종 류 ---</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"100\">일반</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"200\">특보</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"300\">속보</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t<select id=\"news-category\" name=\"newscategory\">\r\n");
      out.write("\t\t\t\t\t\t<option selected value=\"\">---카테고리---</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">시사</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"20\">경제</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"30\">스포츠</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"40\">연예</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t<select id=\"news-location\" name=\"newslocation\">\r\n");
      out.write("\t\t\t\t\t\t<option selected  value=\"\">--- 지 역 ---</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"국내\">국내</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"해외\">해외</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-xs-1 control-label\">제목</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"news-title\" name=\"title\" class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<label class=\"col-xs-1 control-label\">내용</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"ir1\" id=\"ir1\" rows=\"10\" cols=\"100\" style=\"width:100%; height:412px; display:none;\"></textarea>\r\n");
      out.write("\t\t\t\t</div>      \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-1\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10 text-right\">\r\n");
      out.write("\t\t\t\t\t<button id=\"temp-save\" class=\"btn btn-info\">임시저장</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"btn-submit\" class=\"btn btn-success\">작성완료</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div class=\"well picture-container row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t<button class=\"btn\" id=\"btn-hide\"><span class=\"glyphicon glyphicon-menu-right\"></span></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-10 col-xs-offset-1\" id=\"picture-container\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>PictureContainer</legend>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>---카테고리---</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>시사</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>경제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>연예</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>스포츠</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">원본</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">수정본</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 text-center pic-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a onclick=\"javascript:appendContentImg(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/commons/img/school2.png\" class=\"img-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>사진제목</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>작 성 자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 text-center pic-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a onclick=\"javascript:appendContentImg(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/commons/img/school2.png\" class=\"img-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>사진제목</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>작 성 자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 text-center pic-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a onclick=\"javascript:appendContentImg(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/commons/img/school2.png\" class=\"img-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>사진제목</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>작 성 자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 text-center pic-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a onclick=\"javascript:appendContentImg(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/commons/img/school2.png\" class=\"img-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>사진제목</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>작 성 자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 text-center pic-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a onclick=\"javascript:appendContentImg(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/commons/img/school2.png\" class=\"img-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>사진제목</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>작 성 자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 text-center pic-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a onclick=\"javascript:appendContentImg(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/commons/img/school2.png\" class=\"img-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>사진제목</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>작 성 자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t                <ul class=\"pagination pagination-sm\">\r\n");
      out.write("\t                    <li><a href=\"\">&laquo;</a></li>\r\n");
      out.write("\t                    <li><a href=\"\">1</a></li>\r\n");
      out.write("\t                    <li class=\"active\"><a href=\"\">2</a></li>\r\n");
      out.write("\t                    <li><a href=\"\">3</a></li>\r\n");
      out.write("\t                    <li><a href=\"\">4</a></li>\r\n");
      out.write("\t                    <li><a href=\"\">5</a></li>\r\n");
      out.write("\t                    <li><a href=\"\">&raquo;</a></li>\r\n");
      out.write("                \t</ul>\r\n");
      out.write("            \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"bd-footer text-muted\" style=\"bottom:0; width:100%; height:70px;\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row col-xs-2\">\r\n");
      out.write("\t\t\t\t<h2>J Times</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row col-xs-10\">\r\n");
      out.write("    \t\t\t<p>Copyright ⓒ All rights reserved <span class=\"glyphicon glyphicon-phone-alt\" aria-hidden=\"true\">010)1111-1111</span></p>\r\n");
      out.write("    \t\t\t<p>주소: 서울특별시 종로구 율곡로10길 105 디아망 401호(봉익동 10-1 디아망 401호) 등록일자: 20XX.XX.XX 발행인/편집인: 김형택</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
